repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-merge-conflict
  - id: mixed-line-ending
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  - id: detect-private-key
  - id: destroyed-symlinks
  - id: check-symlinks
  - id: check-case-conflict
  - id: check-ast
  - id: double-quote-string-fixer
  - id: requirements-txt-fixer
  - id: check-xml
  - id: check-yaml
  rev: v4.5.0
- repo: https://github.com/codespell-project/codespell
  hooks:
  - id: codespell
    args:
    - --write-changes
  rev: v2.2.6
- repo: https://github.com/hhatto/autopep8
  hooks:
  - id: autopep8
  rev: v2.1.0
- repo: https://github.com/PyCQA/flake8
  hooks:
  - id: flake8
  rev: 7.0.0
- repo: https://github.com/adrienverge/yamllint
  hooks:
  - id: yamllint
    args:
    - --format
    - parsable
    - --strict
  rev: v1.35.1
- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  hooks:
  - id: yamlfmt
    args:
    - --width
    - '120'
    - --implicit_start
    - --implicit_end
    - --mapping
    - '2'
    - --sequence
    - '2'
    - --offset
    - '0'
  rev: 0.2.3
ci:
  autoupdate_schedule: quarterly
